on:
  # Triggers the workflow on pull request events
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs
jobs:
  # Single job called "routers_tests"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Stop existing container
        run: docker stop alarm-bot-tg-client || true

      - name: Remove existing container
        run: docker rm alarm-bot-tg-client || true

      - name: Build Docker image
        run: docker build -t alarm-bot-tg-client .

      - name: Run Docker container
        env:
          BACKEND_HOST: ${{ secrets.BACKEND_HOST }}
          BACKEND_USER_LOGIN: ${{ secrets.BACKEND_USER_LOGIN }}
          BACKEND_USER_PASSWORD: ${{ secrets.BACKEND_USER_PASSWORD }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: docker run -d -p 87:80  --restart always --name alarm-bot-tg-client --env BACKEND_HOST=BACKEND_HOST --env BACKEND_USER_LOGIN=BACKEND_USER_LOGIN --env BACKEND_USER_PASSWORD=BACKEND_USER_PASSWORD --env BOT_TOKEN=BOT_TOKEN alarm-bot-tg-client